appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qV12y8LnHbumYb7FsG2ua0aVUQV+t2LWFmgxpC3x4WJhMDdRufM8GuaLO7jHm5CR9pDyvLNlFPiqu6Rw/2ANFJ1+IcI5ru/KilysDA6QRvuqzDgK4uYBol6DuGdTpj3wSE5eE7tflj/3VhZgZk8wod+5Af1htA8kzjX9IW/K8hwgWqa9mWh4G7+MRWDdINHf43Czg9knnqMk+gQTA1K68EMwjYXPNjwqtCXnI/BOoHMQv+7c60l9Yo/qi9Iqo2M9VdRlbVOkSdXLcOo3LIhcgnfivsjT1oStv7yidYalyM+nNodkgBhDM4/Kg+Miu/0yby0UBZ6kh+22QDxhGPDkbVHtiEOJ/Yl/tVZH1yLm06c0WIRzhStOskLAEoSJIBKf7BblXevALxQ/FTmJO00I2+Cc4ktc210usd+rl9sVIBB/Iboi5MiPRLD40Hx1G7LZDLHR+KZPqFElEhG5/zuvRcbJz4nMB6hDdi5a2aH1Ti/t4nUnBDoALlMwsBB0RE2BWyGKOlpLb5yWziLUrdq2nIp20QTODEqYB5Pzl0wrM9Hab7NYrDAos/NUNAZO8zt7Y+X1lY5V4Ph7KThWAjPNfnBMJx9m76mUUcJPaL+D5Xm15ldFCJnhH45vP0TXVCXDaJzKDr5xdLsdhju/RQLMbEAPvfyiZqJ0WrqaS8VlHI8=}
